

#all tableConfiguration property

#tableName not null
#className defalut STOCK_MONITOR(tableName) -> StockMonitor(className)
#domainPackageName not null
#domainQueryPackageName
#domainObjectName default STOCK_MONITOR(tableName) -> stockMonitor(domainObjectName)
#domainObjectQueryName default "stockMonitorQuery"(domainObjectName+Query)
#domainObjectQueryClassName default ClassName+"Query"
#domainQueryObjectPackageName default domainPackageName+".query"


#daoSuffix  default "Dao"
#daoImplSuffix  default "DaoImpl"
#managerSuffix default "Manager"
#managerImplSuffix default "ManagerImpl"
#mapperSuffix default "_sqlMap"



#daoPackageName not null
#daoPackageName not null
#daoImplPackageName not null
#managerPackageName not null
#managerImplPackageName not null
#sqlMapPath not null
#nameSpace default className
#mapperName default domainObjectName+mapperSuffix+".xml"
#daoSuperClassName default "SqlMapClientDaoSupport"
#managerSuperClassName default ""
#managerName default className+managerSuffix
#managerImplName default className+managerImplSuffix
#daoImplName default className+daoSuffix
#daoImplName className+daoImplSuffix


#selectUsingIdSqlId default "select"+className+"UsingId"
#queryListSqlId default "query"+className+"List"
#queryPageableListSqlId default "queryPageableList"
#insertObjectSqlId default "insert"+className
#updateObjectSqlId default "update"+className
#deleteObjectSqlId default "delete"+className
#selectCountSqlId  default "selectCount"

driverClassName: oracle.jdbc.OracleDriver
user: forall_stock
password: forall_stock
url: jdbc:oracle:thin:@172.21.1.3:1521:dev
projectPath: D:\Application\A∞Ê“’ ı∆∑721\chengdudao\src
tableConfigurationList:
  - tableName: INTENTION_TRADER
    domainPackageName: com.hundsun.wudadao.chengdudao.domain.sample
    domainQueryPackageName: com.hundsun.wudadao.chengdudao.domain.sample.query
    daoPackageName: com.hundsun.wudadao.chengdudao.dao.sample
    daoImplPackageName: com.hundsun.wudadao.chengdudao.dao.sample.ibatis
    managerPackageName: com.hundsun.wudadao.chengdudao.manager.sample
    managerImplPackageName: com.hundsun.wudadao.chengdudao.manager.sample.impl
    sqlMapPath: com.hundsun.wudadao.chengdudao.domain.sample
  - tableName: STOCK_A_QUOTA
    domainPackageName: com.hundsun.wudadao.chengdudao.domain.sample
    domainQueryPackageName: com.hundsun.wudadao.chengdudao.domain.sample.query
    daoPackageName: com.hundsun.wudadao.chengdudao.dao.sample
    daoImplPackageName: com.hundsun.wudadao.chengdudao.dao.sample.ibatis
    managerPackageName: com.hundsun.wudadao.chengdudao.manager.sample
    managerImplPackageName: com.hundsun.wudadao.chengdudao.manager.sample.impl
    sqlMapPath: com.hundsun.wudadao.chengdudao.domain.sample